--- 
jobs: 
  build: 
    docker: 
      - 
        image: "circleci/android:api-28-node8-alpha"
    environment: 
      ANDROID_HOME: /usr/local/android-sdk-linux
      JVM_OPTS: "-Xmx3200m"
    steps: 
      - checkout
      - 
        restore_cache: 
          key: "jars-{{ checksum \"build.gradle\" }}-{{ checksum  \"app/build.gradle\" }}"
      - 
        run: 
          command: "sudo ./gradlew androidDependencies"
          name: "Download Dependencies"
          pre: 
            - "echo y | android update sdk --no-ui --all --filter \"platform-tools, tools\""
            - "echo y | android update sdk --no-ui --all --filter \"android-24, build-tools-25.0.2\""
            - "echo y | android update sdk --no-ui --all --filter \"extra-android-m2repository\""
            - "echo y | android update sdk --no-ui --all --filter \"extra-android-support\""
      - 
        save_cache: 
          key: "jars-{{ checksum \"build.gradle\" }}-{{ checksum  \"app/build.gradle\" }}"
          paths: 
            - ~/.gradle
      - 
        run: 
          command: "sudo ./gradlew testDebug"
          name: "Run Tests"
      - 
        store_artifacts: 
          destination: reports
          path: app/build/reports
      - 
        store_test_results: 
          path: app/build/test-result
    working_directory: ~/repo
version: 2
